### ISSUE TITLE
weird result

### ISSUE THREAD

**Issue by ghost** [YangNaruto/FQ-GAN#5]
I tried the self2anime checkpoint and got this result
![001](https://user-images.githubusercontent.com/6818285/80897250-e57eea00-8cc4-11ea-978b-4ba933c83716.jpg)

**Comment by YangNaruto** [comment]
that's very weird, I will look into it.

**Comment by ghost** [comment]
@YangNaruto can you please make a google colab for inference tests, that will be easier to compare with

**Comment by YangNaruto** [comment]
No problem.

**Comment by YangNaruto** [comment]
@ak9250 I just checked. It seems the model failed to load the checkpoint. I will make it more clear on how to load the checkpoint. Thanks for reminding me of this!

**Comment by ghost** [comment]
@YangNaruto ok thanks, do you get gan.test() epoch is missing parameter in main.py when testing?

**Comment by YangNaruto** [comment]
> @YangNaruto ok thanks, do you get gan.test() epoch is missing parameter in main.py when testing?

fixed. I also clarify how to test the pre-trained model in README for testing purpose.

**Comment by YangNaruto** [comment]
> @YangNaruto can you please make a google colab for inference tests, that will be easier to compare with
 I just created a colab and shared it.

**Comment by ghost** [comment]
@YangNaruto i am still getting
 [*] Reading checkpoints...
 [*] Failed to find a checkpoint
 [!] Load failed...
I have set --checkpoint_dir '/content/drive/My Drive/FQ-gan-checkpoints/'
in the colab I setup, I will try your colab and see

**Comment by YangNaruto** [comment]
you can manually define the ckpt folder in function load of UATIT.py.

**Comment by YangNaruto** [comment]
@ak9250 also remember to download all files in the folder I share.

**Comment by ghost** [comment]
@YangNaruto thanks I got it working in my colab
![55fdc9f0-27c1-4257-80fe-4d9d19274c4e](https://user-images.githubusercontent.com/6818285/80899155-cbe89d00-8cda-11ea-99a2-3a0262456778.jpeg)

**Comment by ghost** [comment]
@YangNaruto photo2portrait also might be missing the checkpoint in google drive

**Comment by YangNaruto** [comment]
@ak9250 fixed. thanks for letting me know.

**Comment by ghost** [comment]
@YangNaruto ValueError: The passed save_path is not a valid checkpoint UGATIT.model-700000

**Comment by YangNaruto** [comment]
> @YangNaruto ValueError: The passed save_path is not a valid checkpoint UGATIT.model-700000

The dataset name should be portrait. So put checkpoints into 
UGATIT_q_portrait_lsgan_4resblock_6dis_1_1_10_10_1000_sn_smoothing_123_2.0_0.85.
